ext {
    extName = 'AniWatch'
    extClass = '.AniWatch'
    extVersionCode = 1
    isNsfw = false
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:vidsrcextractor"))
    implementation(project(":lib:omniembedextractor"))
    implementation(project(":lib:rapidcloudextractor"))
}
